version: '3'

services:
  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: gorm
      POSTGRES_PASSWORD: gorm
      POSTGRES_DB: gorm
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
